/*
 * DIO_cfg.c
 *
 *  Created on: Feb 8, 2025
 *      Author: DELL
 */
#include "DIO_interface.h"
#include "DIO_private.h"
const DioDirection_Type config_pins[NUM_OF_PINS]=
{
		INPUT_FLOATING,     // PINA0
		INPUT_FLOATING,     // PINA1
		INPUT_FLOATING,     // PINA2
		INPUT_FLOATING,     // PINA3
		INPUT_FLOATING,     // PINA4
		INPUT_FLOATING,     // PINA5
		INPUT_FLOATING,// PINA6
		INPUT_FLOATING,// PINA7
		INPUT_FLOATING,// PINB0
		INPUT_FLOATING,// PINB1
		INPUT_FLOATING,// PINB2
		INPUT_FLOATING,// PINB3
		INPUT_FLOATING,// PINB4
		OUTPUT,// PINB5
		OUTPUT,// PINB6
		OUTPUT,// PINB7
		OUTPUT,// PINC0
		OUTPUT,// PINC1
		OUTPUT,// PINC2
		OUTPUT,// PINC3
		OUTPUT,// PINC4
		OUTPUT,// PINC5
		OUTPUT,// PINC6
		OUTPUT,// PINC7
		OUTPUT,// PIND0
		OUTPUT,// PIND1
		OUTPUT,// PIND2
		OUTPUT,// PIND3
		OUTPUT,// PIND4
		OUTPUT,// PIND5
		OUTPUT,// PIND6
		OUTPUT // PIND7

};

